flat_check_as_cran.Rmd:
  path: dev/flat_check_as_cran.Rmd
  state: active
  R: R/check_as_cran.R
  tests: tests/testthat/test-check_as_cran.R
  vignettes: vignettes/check-with-real-cran-settings.Rmd
flat_check_clean_userspace.Rmd:
  path: dev/flat_check_clean_userspace.Rmd
  state: active
  R: R/check_clean_userspace.R
  tests: tests/testthat/test-check_clean_userspace.R
  vignettes: vignettes/no-files-left-after-check.Rmd
  inflate:
    pkg: checkhelper
    flat_file: dev/flat_check_clean_userspace.Rmd
    vignette_name: No files left after check
    open_vignette: no
    check: no
    document: no
    overwrite: ask
flat_create_example_pkg.Rmd:
  path: dev/flat_create_example_pkg.Rmd
  state: active
  R: R/create_example_pkg.R
  tests: tests/testthat/test-create_example_pkg.R
  vignettes: []
flat_deal-with-check-outputs.Rmd:
  path: dev/flat_deal-with-check-outputs.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/deal-with-check-outputs.Rmd
