# WARNING - Generated by {fusen} from dev/flat_check_as_cran.Rmd: do not edit by hand

test_that("check_as_cran works", {
  path <- suppressWarnings(create_pkg())
  check_dir <- tempfile("example")

  if (interactive()) {
    expect_error(check_as_cran(pkg = path, check_dir = check_dir), regexp = NA)
  } else {
    check_callr <- function(pkg, check_dir) {
      library(checkhelper)
      check_as_cran(pkg = pkg, check_dir = check_dir)
    }

    # need to run in another env. inside check in check
    expect_error(callr::r(check_callr, args = list(pkg = path, check_dir = check_dir)), regexp = NA)
  }
  # check_as_cran(pkg = "/mnt/Data/github/ThinkR-open/attachment")
  # Check that env is clean - only manually
  # Sys.getenv("_R_CHECK_AUTOCONF_")
  unlink(check_dir, recursive = TRUE)
})
